name: Update Maker Image
on:
  push:
    branches: [master]

jobs:
  build:
    name: Test & Build
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://errordeveloper/maker:89c330bdfc2bb409e6b62f19e3e8a2417764b983
        name: Run make push-maker-image
        with:
          entrypoint: make
          args: push-maker-image
